name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Compile
        run: ant -noinput -buildfile build.xml compile
      - uses: actions/upload-artifact@v1
        name: Upload Logs
        if: always()
        with:
          name: Logs
          path: outputs/logs
