name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Compile
      run: javac -sourcepath src -d bin src\*.jav
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Bin
        path: bin
