name: Java CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile
        run: mvn -B compile --file pom.xml
      - name: Run Tests
        run: mvn -B site --file pom.xml
      - uses: sebastianpopp/ftp-action@releases/v2
        name: Upload Report to Server
        if: always()
        with:
          host: tommyhosewol.com
          user: github_actions
          password: ${{ secrets.FTP_PASS }}
          localDir: target/site
          remoteDir: ${{ github.run_id }}
      - uses: scacap/action-surefire-report@v1
        name: Publish Test Report
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
