name: Java CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Code Style
        uses: zbeekman/EditorConfig-Action@v1.1.1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          architecture: x64
      - name: Compile
        run: mvn -B compile --file pom.xml
      - name: Run Tests
        run: mvn -B site --file pom.xml
      - uses: actions/upload-artifact@v1
        name: Upload Report to Artifact
        if: always()
        with:
          name: Report
          path: target/site
      - uses: SamKirkland/FTP-Deploy-Action@3.0.0
        name: Upload Report to Server
        if: always()
        with:
          ftp-server: ftp://tommyhosewol.com/${{ github.run_id }}
          ftp-username: github_actions
          ftp-password: ${{ secrets.FTP_PASS }}
          local-dir: target/site
